---
related:
    - develop/submit_issue.adoc
    
---

HubPress uses the Ghost themes to control the look and feel of blogs.

You can use almost any Ghost theme available, providing you map the page assets back into the HubPress theme attributes.

NOTE: The way themes are managed will change from Release 8.

If you look into the theme folders, you'll see a mapping file named `theme.js`.

[source,json]
----
{
  "files": {
    "author": "author.hbs",
    "default": "default.hbs",
    "index": "index.hbs",
    "page": "page.hbs",
    "post": "post.hbs",
    "tag": "tag.hbs",
    "links": "partials/links.hbs",
    "footer": "partials/footer.hbs",
    "loop": "partials/loop.hbs"
  },
  "version":"1.0.0"
}
----

You map the Ghost theme `.hbs` assets back into the HubPress page parameters.

If you want to modify a theme shipped with HubPress, you should *never* alter a theme without making a copy first.
If you don't you may have issues with updating HubPress easily in the future because of merge conflicts between the modified shipped themes.

If you want to contribute a theme, create a request in the https://github.com/HubPress/hubpress.io/issues[HubPress.io Bug Tracker] and we'll help you.

There may also be other edge-cases in the Ghost themes you select. Once such example is in https://github.com/HubPress/hubpress.io/issues/55[Issue #55] where the `contentFor` requirement required some compromises.
